CREATE TABLE CAL_SCH (
SCH_NO NUMBER PRIMARY KEY,
MEM_NUM VARCHAR2(50),
CAL_NO VARCHAR2(30),
SCH_NAME VARCHAR2(30)NOT NULL,
SCH_START_DATE DATE NOT NULL,
SCH_START_TIME VARCHAR2(5),
SCH_END_DATE DATE NOT NULL,
SCH_END_TIME VARCHAR2(5),
SCH_CONTENT VARCHAR2(500), 
AL_STATUS CHAR(1) 
);


DROP TABLE CAL_SCH;

CREATE TABLE CALENDAR(
CAL_NO VARCHAR2(30) PRIMARY KEY,
SCH_NO NUMBER NOT NULL,
MEM_NUM VARCHAR2(50) NOT NULL,
CAL_NAME VARCHAR2(30) NOT NULL,
MEM_NAME VARCHAR2(30),
MEM_DIVISION VARCHAR2(30),
MEM_RANK VARCHAR2(30)
);

CREATE TABLE CAL_BMK (
CAL_NO VARCHAR2(30) PRIMARY KEY,
SCH_NO NUMBER NOT NULL,
MEM_NUM VARCHAR2(50) NOT NULL,
CAL_NAME VARCHAR2(30) NOT NULL,
MEM_NAME VARCHAR2(30),
MEM_DIVISION VARCHAR2(30),
MEM_RANK VARCHAR2(30),
C_STATUS CHAR(2)
);

CREATE TABLE CAL_MEM (
MEM_NUM VARCHAR2(50) PRIMARY KEY,
CAL_NO VARCHAR2(30)NOT NULL,
SCH_NO NUMBER NOT NULL,
CAL_NAME VARCHAR2(30) NOT NULL,
MEM_NAME VARCHAR2(30),
MEM_DIVISION VARCHAR2(30),
MEM_RANK VARCHAR2(30)
);


DROP TABLE CALENDAR;
DROP TABLE CAL_BMK;
DROP TABLE CAL_SCH;
DROP TABLE CAL_MEM;


CREATE TABLE MAIL (
MAIL_NO NUMBER PRIMARY KEY,
MAIL_TYPE VARCHAR2(1) NOT NULL,
MAIL_SUBJECT VARCHAR2(50) NOT NULL,
MAIL_CONTENT VARCHAR2(100),
MAIL_COUNT NUMBER,
MAIL_SENDER VARCHAR2(30) NOT NULL,
MAIL_FROM_ADDR VARCHAR2(50) NOT NULL,
R_STATUS NUMBER DEFAULT 0,
I_STATUS NUMBER DEFAULT 0,
READ_TYPE NUMBER DEFAULT 0,
F_STATUS NUMBER DEFAULT 0,
MAIL_FROM_DATE DATE,
MAIL_TO_DATE DATE,
A_STATUS VARCHAR2(6) DEFAULT '대기',
A_DATE DATE,
REJ_REASON VARCHAR2(100),
RES_DATE DATE,
RES_HOUR CHAR(2),
RES_MIN CHAR(2),
MEM_NUM VARCHAR2(50)
);

DROP TABLE MAIL;

CREATE TABLE MAIL_REF (
MAIL_NO NUMBER,
MAIL_REFEREE VARCHAR2(50),
REF_NO NUMBER,
MAIL_TO_ADDR VARCHAR2(50)
);

CREATE TABLE MAIL_REC (
MAIL_NO NUMBER,
MAIL_RECEIVER VARCHAR2(50),
REC_NO NUMBER,
MAIL_TO_ADDR VARCHAR2(50) 
);
DROP TABLE MAIL_REC;

CREATE TABLE MAIL_BMK (
BMK_NO NUMBER PRIMARY KEY,
MAIL_NO NUMBER,
BMK_SUBJECT VARCHAR2(50) NOT NULL,
BMK_NAME VARCHAR2(50) NOT NULL,
BMK_ADDR VARCHAR2(50) NOT NULL,
MEM_NUM VARCHAR2(50) NOT NULL
);

CREATE TABLE MAIL_FILE (
MAIL_FILENO NUMBER PRIMARY KEY,
MAIL_NO NUMBER,
MAIL_FILENAME VARCHAR2(100),
MAIL_FILERENAME VARCHAR2(100),
MAIL_FILECOUNT NUMBER,
MAIL_FILEPATH VARCHAR2(100),
MEM_NUM VARCHAR2(50)
);

CREATE SEQUENCE SEQ_SCH_NO; 
CREATE SEQUENCE SEQ_MAIL_NO;
CREATE SEQUENCE SEQ_REC_NO;
CREATE SEQUENCE SEQ_REF_NO;
CREATE SEQUENCE SEQ_MAIL_FILE_NO;

INSERT ALL INTO MAIL(MAIL_NO,MAIL_TYPE, MAIL_SUBJECT, MAIL_CONTENT, MAIL_SENDER, MAIL_FROM_ADDR, MAIL_FROM_DATE, MEM_NUM) 
VALUES(1, 'Y','11', '111', '11', 'DWFWFWRF', SYSDATE, 3) 
INTO MAIL_REF(MAIL_NO, MAIL_REFEREE, REF_NO, MAIL_TO_ADDR) VALUES(1, '111', 1, 'DEDEW')
INTO  MAIL_REC(MAIL_NO, MAIL_RECEIVER, REC_NO, MAIL_TO_ADDR) VALUES(1, '1111', 1, 'WDEWF') SELECT * FROM DUAL;
            
		 ROLLBACK;




SELECT M.MAIL_NO, M.MAIL_SENDER, M.MAIL_SUBJECT, M.MAIL_CONTENT, M.MAIL_FROM_DATE, R.MAIL_RECEIVER 
FROM MAIL M 
JOIN MAIL_REC R ON(M.MAIL_NO = R.MAIL_NO) 
WHERE R.MAIL_RECEIVER = 'receiver1' 
AND
 M.MAIL_TYPE = 'T'
ORDER BY M.MAIL_NO DESC;


DELETE FROM DUAL WHERE MAIL_NO = '7';


			SELECT M.MAIL_NO, M.MAIL_SENDER, M.MAIL_SUBJECT, M.MAIL_CONTENT, E.MAIL_FILE_RENAME, M.MAIL_TO_DATE, 
            C.MAIL_RECEIVER, C.REC_NO, F.MAIL_REFEREE, F.REF_NO 
            FROM MAIL M
            JOIN MAIL_REC C ON(M.MAIL_NO = C.MAIL_NO) 
            JOIN MAIL_REF F ON (M.MAIL_NO = F.MAIL_NO)
            JOIN MAIL_FILE E ON (M.MAIL_NO = E.MAIL_NO) 
            WHERE M.MAIL_NO = '22';
            
            
            UPDATE MAIL_REF SET MAIL_REFEREE = 'receiver3'  WHERE MAIL_NO = '17';
            
            
SELECT * FROM
(SELECT MAIL_NO, I_STATUS, READ_TYPE, F_STATUS, MAIL_SENDER, MAIL_SUBJECT, MAIL_FROM_DATE
			 FROM MAIL WHERE MAIL_TYPE = 'S')
JOIN MAIL_REC USING(MAIL_NO)
WHERE MAIL_RECEIVER = 'admin,';


SELECT MAIL_NO, I_STATUS, READ_TYPE, F_STATUS, MAIL_SENDER, MAIL_SUBJECT, MAIL_FROM_DATE
			 FROM MAIL WHERE MAIL_TYPE = 'S' AND MAIL_SENDER = 'admin';
SELECT * FROM          
(SELECT * FROM
			(SELECT MAIL_NO, I_STATUS, READ_TYPE, F_STATUS, MAIL_SENDER, MAIL_SUBJECT, MAIL_FROM_DATE
			 FROM MAIL)
			JOIN MAIL_FILE USING(MAIL_NO))
            JOIN MAIL_REC USING(MAIL_NO)
			WHERE MAIL_RECEIVER = 'admin,' OR MAIL_SENDER = 'admin';
            
            
            SELECT * FROM
			(SELECT MAIL_NO, I_STATUS, READ_TYPE, F_STATUS, MAIL_SENDER, MAIL_SUBJECT, MAIL_FROM_DATE
			 FROM MAIL WHERE MAIL_TYPE = 'S')
			JOIN MAIL_REC USING(MAIL_NO)
			WHERE MAIL_RECEIVER = 'admin,' AND MAIL_SENDER = 'admin';